### ISSUE TITLE
Feature request: use voxels for non-voxelized pickups

### ISSUE THREAD

**Issue by poperigby** [MajorCooke/Doom4DoomResources#3]
Some pickups use a highly detailed 3D model for their pickup (like the armor and health bonuses), making them into voxel models would make the mod more visually consistent with Doom.

**Comment by MajorCooke** [comment]
They used to have voxels but I changed them to models. 2.0.3 has all the voxels you want.

3.0 aims to replace them all because voxels are worse for performance. Still working on replacing the rest of them. with real models.

**Comment by poperigby** [comment]
That sucks. Voxels look really cool. Hope GZDoom can improve their performance in the future.

**Comment by MajorCooke** [comment]
This affects anything that has voxels for any engine. Each individual square on a voxel is counted as an independent model. There is no optimizing this.

**Comment by poperigby** [comment]
Then how do games made entirely with voxels run?

**Comment by MajorCooke** [comment]
¯\_(ツ)_/¯

All I know is what I'm told by some of the more expert modders and developers on GZDoom. And they were right.

Furthermore, the real models allow for more realistic lighting effects for those who enjoy them, especially if they use GL lights. It actually looks fantastic.

**Comment by poperigby** [comment]
I do agree that they look cool, it's just the visual inconsistency is a little strange. That's all.
